apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-db-from-kafka
  namespace: netpol
spec:
  podSelector:
    matchLabels:
      app: database-server
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kafka-server
      ports:
        - port: 80
        - port: 443
