apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-kafka-from-web
  namespace: netpol
spec:
  podSelector:
    matchLabels:
      app: kafka-server
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: web-server
      ports:
        - port: 80
