apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd-demo
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: fluxcd-demo
  targetNamespace: fluxcd-demo
  chart:
    git: git@github.com:pavan-kumar-99/kustomize-demo.git
    path: helm-charts/fluxcd-demo
    ref: fluxcd-demo
